version: '3.7'

services:
  weather:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - weather_db
  
  weather_db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weather
      - POSTGRES_DB=weather_dev

  celery:
    build: ./app
    command: celery worker --app=weather_reminder --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env.dev
    depends_on:
      - weather
      - redis
  
  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
